spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${PORT_NUMBER}/${DB_NAME}?serverTimezone=UTC&characterEncoding=UTF-8
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true  # (3) SQL pretty print
  logging:
    level:
      org:
        springframework:
          orm:
            jpa: DEBUG
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: ${CLIENT_ID}
#            client-secret: ${CLIENT_SECRET}
#            scope:
#              - profile
#              - email
#jwt:
#  secret: ${JWT_SECRET}
#  access_token_expired: 3_600_000
#  refresh_token_expired: 604_800_000